# Generated by Django 5.2.8 on 2025-11-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('create', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=20)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
