# Generated by Django 5.2.8 on 2025-11-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='top_images/'),
        ),
    ]
