# Generated by Django 5.2.8 on 2025-11-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_top_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desk', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=15)),
                ('age', models.IntegerField(null=True)),
                ('stady_start', models.DateField(null=True)),
                ('stady_finish', models.DateField(null=True)),
                ('kurs', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='top',
        ),
    ]
