# Generated by Django 5.2.8 on 2025-11-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_sertificat_student_delete_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='kurs',
            new_name='category',
        ),
    ]
