# Generated by Django 5.2.8 on 2025-11-23 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_rename_kurs_student_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.kurs'),
        ),
    ]
