# Generated by Django 5.2.8 on 2025-11-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_jobrequest_stadyrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('social', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=60)),
                ('logo_comp', models.ImageField(upload_to='logo_comp/')),
            ],
        ),
        migrations.CreateModel(
            name='StudyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='StadyRequest',
        ),
    ]
