# Generated by Django 5.2.8 on 2025-12-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_contacts_studyrequest_delete_stadyrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='stady_finish',
            new_name='study_finish',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='stady_start',
            new_name='study_start',
        ),
    ]
